services:
  - type: web
    name: bg-remover-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: FRONTEND_URL
        value: https://bg-remover.vercel.app  # Your real frontend URL