services:
  - type: web
    name: profile-photo-styler-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1